version: '3'

services:
  api:
    image: node:12.13
    command: ['api/node_modules/node-dev/bin/node-dev', 'api/bin/start.js']
    working_dir: /usr/src
    restart: on-failure:5
    env_file:
      - docker.env
    environment:
      - PORT=8080
      - E2E_TEST=$E2E_TEST
      - AUTH0_BASE_URL=$AUTH0_BASE_URL
      - LOG_LEVEL=debug
    ports:
      - 8080:8080
      - 3333:3333
    volumes:
      - .:/usr/src
    networks:
      - storage

  db:
    image: postgres:10.3
    ports:
      - 5433:5432
    environment:
      - POSTGRES_DB=traitdunion-e2e
      - POSTGRES_USER=trait
      - POSTGRES_PASSWORD=dunion
    networks:
      - storage

networks:
  storage:
    driver: bridge
