version: '3'

services:
  api:
    image: node:10.15.3
    command: ['node', 'api']
    working_dir: /usr/src/api
    restart: always
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/api
    env_file:
      - api/.int.env
    networks:
      - storage

  db:
    image: postgres:9.6.8
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=traitdunion-database
      - POSTGRES_USER=trait
      - POSTGRES_PASSWORD=dunion
    networks:
      - storage

networks:
  storage:
    driver: bridge
