version: '3'

services:
  api:
    image: node:12.13
    command: 'api/node_modules/node-dev/bin/node-dev --all-deps  api/bin/start.js'
    working_dir: /usr/src
    restart: on-failure:5
    env_file:
      - docker.env
    environment:
      - PORT=8080
      - E2E_TEST=$E2E_TEST
      - AUTH0_BASE_URL=$AUTH0_BASE_URL
      - LOG_LEVEL=debug
      - ALLOWED_ORIGIN=$ALLOWED_ORIGIN
      - PE_API_BASE_URL=$PE_API_BASE_URL
      - PE_AUTHENT_API_BASE_URL=$PE_AUTHENT_API_BASE_URL
      - PE_CLIENT_ID=$PE_CLIENT_ID
      - PE_CLIENT_SECRET=$PE_CLIENT_SECRET
      - SENDINBLUE_API_KEY=$SENDINBLUE_API_KEY
      - TU_FF_NOTIFY_ON_SLACK=$TU_FF_NOTIFY_ON_SLACK
      - SLACK_HOOK_URL=$SLACK_HOOK_URL
      - SLACK_NOTIFICATION_CHANNEL=$SLACK_NOTIFICATION_CHANNEL
      - TU_FF_USE_REAL_SENDINBLUE=$TU_FF_USE_REAL_SENDINBLUE
      - TU_FF_SCHEDULE_SOURCING=$TU_FF_SCHEDULE_SOURCING
      - CANDIDATURE_RECEIVED_HOOK_URL=$CANDIDATURE_RECEIVED_HOOK_URL
      - OFFRE_PUBLISHED_HOOK_URL=$OFFRE_PUBLISHED_HOOK_URL
      - COOKIE_PASSWORD=$COOKIE_PASSWORD
    ports:
      - 8080:8080
      - 3333:3333
    volumes:
      - .:/usr/src
    networks:
      - storage

  db:
    image: postgres:10.3
    ports:
      - 5433:5432
    environment:
      - POSTGRES_DB=traitdunion-e2e
      - POSTGRES_USER=trait
      - POSTGRES_PASSWORD=dunion
    networks:
      - storage

networks:
  storage:
    driver: bridge
