workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - checkout_code:
          filters:
            branches:
              only: staging
      - install_dependencies:
          requires:
            - checkout_code
      - lint:
          requires:
            - install_dependencies
      - test:
          requires:
            - install_dependencies
      - deploy_to_staging:
          requires:
            - lint
            - test
      - ready_for_production:
          type: approval # Manual approval is required to deploy to production
          requires:
            - deploy_to_staging

      - deploy_to_production:
          requires:
            - ready_for_production

defaults: &defaults
  docker:
    - image: circleci/node:10.15.3-browsers
      environment:
        JOBS: 1
  working_directory: ~/project

version: 2
jobs:
  checkout_code:
    <<: *defaults
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths:
            - .

  install_dependencies:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - restore_cache:
          keys:
            - traitdunion-node10-v1-{{ checksum "package-lock.json" }}-{{ checksum "api/package-lock.json" }}-{{ checksum "front/package-lock.json" }}
      - run: npm config set spin false
      - run:
          name: Update NPM to latest version
          command: sudo npm install -g npm@latest
      - run:
          name: Check npm and node version
          command: |
            node --version
            npm --version
      - run:
          name: NPM Install
          command: |
            GIT_SSH_COMMAND="ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no" npm install
      - save_cache:
          key: traitdunion-node10-v1-{{ checksum "package-lock.json" }}-{{ checksum "api/package-lock.json" }}-{{ checksum "front/package-lock.json" }}
          paths:
            - ~/project/node_modules
            - ~/project/api/node_modules
            - ~/project/front/node_modules
      - persist_to_workspace:
          root: .
          paths:
            - .
      - run:
          name: Ensure git status is empty
          command: |
            git status --porcelain
            git diff

  lint:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Lint
          command: npm run lint

  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Run Tests
          command: npm run test

  deploy_to_staging:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - add_ssh_keys:
          fingerprints:
            - "17:26:2d:c8:49:c4:19:cc:83:83:78:91:9c:75:e9:d3"
      - run:
          name: Update version
          command: |
            git status
            git config credential.helper 'cache --timeout=120'
            git config user.email "circle-ci@traitdunion.fr"
            git config user.name "Circle CI"
            npm version patch -m "Deploy %s [skip ci]"
            git status
            git push -q https://${GITHUB_TOKEN}@github.com/betagouv/trait-d-union.git staging
            git status
            git push -q https://${GITHUB_TOKEN}@github.com/betagouv/trait-d-union.git --tags
      - run:
          name: Deploy to scalingo staging instance
          command: |
            GIT_SSH_COMMAND="ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no" git push git@scalingo.com:traitdunion-staging.git staging:master
            GIT_SSH_COMMAND="ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no" git push git@scalingo.com:api-traitdunion-staging.git staging:master

  deploy_to_production:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - add_ssh_keys:
          fingerprints:
            - "17:26:2d:c8:49:c4:19:cc:83:83:78:91:9c:75:e9:d3"
      - run:
          name: Merge staging to master
          command: |
            git status
            git config credential.helper 'cache --timeout=120'
            git config user.email "circle-ci@traitdunion.fr"
            git config user.name "Circle CI"
            git checkout master
            git merge --no-ff staging
            git status
            git push -q https://${GITHUB_TOKEN}@github.com/betagouv/trait-d-union.git master
      - run:
          name: Deploy to scalingo production instance
          command: |
            GIT_SSH_COMMAND="ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no" git push git@scalingo.com:traitdunion.git master
            GIT_SSH_COMMAND="ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no" git push git@scalingo.com:api-traitdunion.git master
