workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - checkout_code
      - install_dependencies:
          requires:
            - checkout_code
      - lint:
          requires:
            - install_dependencies
      - test:
          requires:
            - install_dependencies
      - deploy:
          requires:
            - lint
            - test

defaults: &defaults
  docker:
    - image: circleci/node:10-browsers
      environment:
        JOBS: 2
  working_directory: ~/project
  parallelism: 3

version: 2
jobs:
  checkout_code:
    <<: *defaults
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths:
            - .

  install_dependencies:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - restore_cache:
          keys:
            - traitdunion-node10-v1-{{ checksum "package-lock.json" }}
      - run: npm config set spin false
      - run:
          name: NPM Install
          command: npm install
      - save_cache:
          key: traitdunion-node10-v1-{{ checksum "package-lock.json" }}
          paths:
            - ~/project/node_modules
            - ~/project/api/node_modules
            - ~/project/front/node_modules
      - persist_to_workspace:
          root: .
          paths:
            - .

  lint:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Lint
          command: npm run lint

  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Run Tests
          command: npm run test

  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - add_ssh_keys:
          fingerprints:
            - "17:26:2d:c8:49:c4:19:cc:83:83:78:91:9c:75:e9:d3"
      - run:
          name: Update version
          command: |
            node -v
            npm -v
            cat front/package-lock.json
            git status
            git config credential.helper 'cache --timeout=120'
            git config user.email "circle-ci@traitdunion.fr"
            git config user.name "Circle CI"
            npm version patch
            git push -q https://${GITHUB_TOKEN}@github.com/betagouv/trait-d-union.git master
            git push -q https://${GITHUB_TOKEN}@github.com/betagouv/trait-d-union.git --tags
      - run:
          name: Deploy to scalingo production instance
          command: GIT_SSH_COMMAND="ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no" git push git@scalingo.com:traitdunion.git master